
db.define_table('Transaction_Prefix',    
    Field('prefix', length = 10, requires = [IS_UPPER(), IS_NOT_EMPTY()]), 
    Field('prefix_name','string', length = 30, requires = [IS_UPPER(), IS_NOT_EMPTY()]),    
    Field('current_year_serial_key', 'integer'),
    Field('previous_year_serial_key', 'integer', writable = False),
    Field('prefix_key','string', length = 10, requires = [IS_UPPER(), IS_NOT_EMPTY()]), 
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(prefix)s')

db.define_table('Account_Transaction_Type', # receipt voucher, payment voucher, journal voucher
    Field('account_transaction_code','string',length=10),
    Field('account_transaction_name','string',length=50),
    Field('created_on','datetime', default=request.now, writable = False, readable = False),
    Field('created_by',db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on','datetime', update=request.now, writable = False, readable = False),
    Field('updated_by',db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(account_transaction_code)s')

db.define_table('Account_Payment_Mode', # cash, cash cheque, post-dated-cheque
    Field('payment_code','string',length=5),
    Field('payment_name','string',length=50),
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(payment_code)s')

db.define_table('Department',    
    Field('department_code','string', length = 5, label ='Department Code', requires = IS_NOT_IN_DB(db, 'Department.department_code')),
    Field('department_name','string', length = 50, label = 'Department Name', requires = [IS_UPPER(), IS_NOT_IN_DB(db, 'Department.department_name')]),    
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False),format = '%(department_code)s')

db.define_table('Account_Voucher', #ondelete = 'NO ACTION', requires = IS_IN_DB(db, db.Department.id, '%(department_code)s - %(department_name)s', zero = 'Choose Department')),
    Field('account_transaction_code_id','reference Account_Transaction_Type',ondelete='NO ACTION',requires=IS_IN_DB(db,db.Account_Transaction_Type.id,'%(account_transaction_code)',zero='Choose Account Code')),
    Field('reference_date','date',default=request.now),
    Field('reference_no','integer'),
    Field('account_payment_mode_id','reference Account_Payment_Mode',ondelete='NO ACTION',requires=IS_IN_DB(db,db.Account_Payment_Mode.id,'%(payment_code)', zero='Choose Payment Code')),
    Field('total_amount','decimal(10,2)',default=0),
    Field('account_code_id','string',length=10),
    Field('bank_name','string',length=50),
    Field('cheque_no','string',length=15),
    Field('cheque_date','date',default=request.now),
    Field('purpose','integer'),
    Field('post_ref_no','string',length=10),
    Field('person','string',length=20),
    Field('entry_date','date',default=request.now),
    Field('cost_center','string',length=15),
    Field('location_center','string',length=5),
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(reference_no)s')

db.define_table('Account_Transaction',
    Field('account_voucher_id','reference Account_Voucher'),
    Field('account_transaction_type_id','string'),
    Field('department_id','reference Department',ondelete='NO ACTION',requires=IS_IN_DB(db,db.Department.id,'%(department_code)',zero='Choose Department')),    
    Field('voucher_reference','string',length=10),
    Field('amount_paid','decimal(10,2)',default=0),
    Field('description','string',length=50),
    Field('account_credit_code','string',length=10),
    Field('account_debit_code','string',length=10),
    Field('account_type','integer',length=1),
    Field('account_reference','integer',length=10),
    Field('account_date','date',default=request.now),
    Field('bank_code','string',length=10),
    Field('person','string',length=50),
    Field('entry_date','date',default=request.now),
    Field('user','string',length=10),
    Field('cost_center','string',length=15),
    Field('location_center','string',length=5),
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(sector)s')

db.define_table('acctvou',
    Field('type','integer'),
    Field('refdte','date',default=request.now),
    Field('refno','integer'),
    Field('modeofpay','integer'),
    Field('totalamount','decimal(10,2)',default=0),
    Field('acctcode','string',length=10),
    Field('bankname','string',length=50),
    Field('chequeno','string',length=15),
    Field('dated','date',default=request.now),
    Field('purpose','integer'),
    Field('postrefno','string',length=10),
    Field('person','string',length=20),
    Field('entrydate','date',default=request.now),
    Field('ccent','string',length=15),
    Field('loccent','string',length=5),
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(sector)s')

db.define_table('accttrn',
    Field('department','integer'),
    Field('voutype','integer'),
    Field('vouref','string',length=10),
    Field('amntpaid','decimal(10,2)',default=0),
    Field('descript','string',length=50),
    Field('acctcrcode','string',length=10),
    Field('acctdbcode','string',length=10),
    Field('accstype','integer',length=1),
    Field('accsref','integer',length=10),
    Field('accsdte','date',default=request.now),
    Field('bankcode','string',length=10),
    Field('person','string',length=50),
    Field('entrydte','date',default=request.now),
    Field('user','string',length=10),
    Field('ccent','string',length=15),
    Field('loccent','string',length=5),
    Field('created_on', 'datetime', default=request.now, writable = False, readable = False),
    Field('created_by', db.auth_user, ondelete = 'NO ACTION', default=auth.user_id, writable = False, readable = False),
    Field('updated_on', 'datetime', update=request.now, writable = False, readable = False),
    Field('updated_by', db.auth_user, ondelete = 'NO ACTION', update=auth.user_id, writable = False, readable = False), format = '%(sector)s')

